./reduction --kernel=0 -type=int 
./reduction --kernel=1 -type=int
./reduction --kernel=2 -type=int
./reduction --kernel=3 -type=int
./reduction --kernel=4 -type=int
./reduction --kernel=5 -type=int
./reduction --kernel=6 -type=int
./reduction --kernel=0 -type=float 
./reduction --kernel=1 -type=float
./reduction --kernel=2 -type=float
./reduction --kernel=3 -type=float
./reduction --kernel=4 -type=float
./reduction --kernel=5 -type=float
./reduction --kernel=6 -type=float
./reduction --kernel=0 -type=double 
./reduction --kernel=1 -type=double
./reduction --kernel=2 -type=double
./reduction --kernel=3 -type=double
./reduction --kernel=4 -type=double
./reduction --kernel=5 -type=double
./reduction --kernel=6 -type=double
